# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Karmus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'FirebaseStorage'
pod 'FirebaseInAppMessaging'
pod 'FirebaseDatabase'

  # Pods for Karmus


end
